-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.consiglilibri
(
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_libro_referenced integer NOT NULL,
    id_libro_suggested integer NOT NULL,
    CONSTRAINT consiglilibri_pkey PRIMARY KEY (user_id, id_libro_referenced, id_libro_suggested)
    );

CREATE TABLE IF NOT EXISTS public.librerie
(
    id_libreria serial NOT NULL,
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT librerie_pkey PRIMARY KEY (id_libreria)
    );

CREATE TABLE IF NOT EXISTS public.librerie_libri
(
    id_libreria integer NOT NULL,
    id_libro integer NOT NULL,
    CONSTRAINT librerie_libri_pkey PRIMARY KEY (id_libreria, id_libro)
    );

CREATE TABLE IF NOT EXISTS public.libri
(
    id_libro integer NOT NULL,
    titolo character varying(1000) COLLATE pg_catalog."default",
    autore character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    categoria character varying(1000) COLLATE pg_catalog."default",
    editore character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    anno_pubblicazione integer NOT NULL,
    copertina character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT libri_pkey PRIMARY KEY (id_libro)
    );

CREATE TABLE IF NOT EXISTS public.utentiregistrati
(
    nome character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cognome character varying(20) COLLATE pg_catalog."default" NOT NULL,
    codice_fiscale character(16) COLLATE pg_catalog."default" NOT NULL,
    mail character varying(30) COLLATE pg_catalog."default" NOT NULL,
    crypted_pass character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT utentiregistrati_pkey PRIMARY KEY (user_id)
    );

CREATE TABLE IF NOT EXISTS public.valutazionilibri
(
    id_valutazione serial NOT NULL,
    user_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_libro integer NOT NULL,
    stile integer NOT NULL,
    contenuto integer NOT NULL,
    gradevolezza integer NOT NULL,
    originalita integer NOT NULL,
    edizione integer NOT NULL,
    votofinale integer NOT NULL,
    recensione character varying(256) COLLATE pg_catalog."default",
    CONSTRAINT valutazionilibri_pkey PRIMARY KEY (id_valutazione),
    CONSTRAINT unique_user_book UNIQUE (user_id, id_libro)
    );

ALTER TABLE IF EXISTS public.consiglilibri
    ADD CONSTRAINT consiglilibri_id_libro_referenced_fkey FOREIGN KEY (id_libro_referenced)
    REFERENCES public.libri (id_libro) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.consiglilibri
    ADD CONSTRAINT consiglilibri_id_libro_suggested_fkey FOREIGN KEY (id_libro_suggested)
    REFERENCES public.libri (id_libro) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.consiglilibri
    ADD CONSTRAINT consiglilibri_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.utentiregistrati (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.librerie
    ADD CONSTRAINT librerie_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.utentiregistrati (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.librerie_libri
    ADD CONSTRAINT fk_libreria FOREIGN KEY (id_libreria)
    REFERENCES public.librerie (id_libreria) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.librerie_libri
    ADD CONSTRAINT fk_libro FOREIGN KEY (id_libro)
    REFERENCES public.libri (id_libro) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.valutazionilibri
    ADD CONSTRAINT fk_valutazione_libro FOREIGN KEY (id_libro)
    REFERENCES public.libri (id_libro) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.valutazionilibri
    ADD CONSTRAINT fk_valutazione_user FOREIGN KEY (user_id)
    REFERENCES public.utentiregistrati (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;